version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: restaurant_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_pass
      MYSQL_DATABASE: restaurant_db
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: ./RestaurantProject
    container_name: RestaurantProject
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://restaurant_user:restaurant_pass@db:3306/restaurant_db
    ports:
      - "80:80"
    volumes:
      - ./RestaurantProject:/var/www/html
    labels:
      - logging="promtail"
    # command: ["apache2-foreground"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  mariadb_data:
  grafana_data:
  loki_data: