version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  db:
    image: mariadb:latest
    container_name: restaurant_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_pass
      MYSQL_DATABASE: restaurant_db
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: ./RestaurantProject
    container_name: RestaurantProject
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://restaurant_user:restaurant_pass@db:3306/restaurant_db
    ports:
      - "80:80"
    volumes:
      - ./RestaurantProject:/var/www/html
    labels:
      - "logging=promtail"
      - "logging_jobname=RestaurantProject"
    # command: ["apache2-foreground"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
    #networks:
      #- app
    logging: *default-logging

  promtail:
    image:  grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./docker-config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yml
    depends_on:
      - loki
    #networks:
      #- app
    logging: *default-logging

volumes:
  mariadb_data:
  grafana_data:
  #loki_data:
