global:
  scrape_interval: 15s  # Seberapa sering Prometheus mengambil data dari target

scrape_configs:
  # Monitoring Prometheus itu sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitoring Node Exporter (untuk metric sistem seperti CPU, RAM, Disk)
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
      
  # Monitoring Aplikasi PHP (jika aplikasi memiliki endpoint metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]