name: Deploy to Server

on:
  push:
    branches:
      - master  # Sesuaikan dengan branch yang ingin digunakan untuk deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy with Docker Compose
        run: |
          ssh $SSH_USER@$SSH_HOST << EOF
            cd /path/to/project
            git pull origin main
            docker compose down
            docker compose pull
            docker compose up -d --build
          EOF

        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}

